sudo: required
language: node_js
node_js:
  - '9'
cache:
  directories:
    - node_modules
install:
  - npm install truffle
  - npm install ganache-cli
  - npm install
script:
  - cd truffle
  - truffle migrate
  - truffle test
after_script:
