sudo: required
language: node_js
node_js:
  - '9'
cache:
  directories:
    - node_modules
before_script: cd truffle

install:
  - npm install truffle
  - npm install ganache-cli
  - npm install
script:
  - ./node_modules/.bin/truffle migrate
  - ./node_modules/.bin/truffle test
after_script:
