import { library } from '@fortawesome/fontawesome-svg-core';
import { fab, faEthereum } from '@fortawesome/free-brands-svg-icons';
import {
  faHome,
  faTimes,
  faLink,
  faBan,
  faQrcode,
  faBuilding,
  faHistory,
  faScroll,
  faPlus,
  faCheck,
  faTruckLoading,
  faTruckMoving,
  faTh,
  faCheckDouble,
  faParachuteBox,
  faLightbulb,
  faDotCircle,
  faDrawPolygon,
  faBoxes,
  faTruck,
  faDownload,
  faTrash,
  faBox,
  faIndustry,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  fab,
  faHome,
  faTimes,
  faLink,
  faBan,
  faHistory,
  faQrcode,
  faBuilding,
  faScroll,
  faPlus,
  faCheck,
  faTruck,
  faTruckLoading,
  faTruckMoving,
  faParachuteBox,
  faCheckDouble,
  faTh,
  faLightbulb,
  faEthereum,
  faDotCircle,
  faDrawPolygon,
  faBoxes,
  faDownload,
  faTrash,
  faBox,
  faIndustry
);
